# Generated by Django 5.0 on 2024-01-16 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0006_alter_level_level_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_title', models.CharField(max_length=255)),
                ('question_description', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('question_helping_video', models.CharField(max_length=100)),
                ('question_image', models.ImageField(upload_to='questions_images')),
                ('question_countdown_time', models.IntegerField()),
                ('question_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminDashboard.level')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
