# Generated by Django 5.0 on 2024-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0007_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_helping_video',
            field=models.TextField(),
        ),
    ]
