# Generated by Django 5.0 on 2024-01-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_title', models.CharField(max_length=100)),
                ('category_description', models.TextField()),
                ('category_image', models.ImageField(upload_to='category_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
