# Generated by Django 5.0 on 2024-01-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0002_alter_category_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_no', models.IntegerField(unique=True)),
                ('number_of_questions', models.IntegerField()),
                ('level_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminDashboard.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
