# Generated by Django 5.0 on 2024-01-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0003_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_no',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('level_no', 'level_category')},
        ),
    ]
