# Generated by Django 5.0 on 2024-01-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0004_alter_level_level_no_alter_level_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=100),
        ),
    ]
