# Generated by Django 5.0 on 2024-01-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0005_alter_category_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminDashboard.category'),
        ),
    ]
