# Generated by Django 5.0 on 2024-01-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0008_alter_question_question_helping_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_countdown_time',
            field=models.PositiveIntegerField(),
        ),
    ]
