# Generated by Django 5.0 on 2024-01-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0014_answer_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_countdown_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_title',
        ),
    ]
