# Generated by Django 5.0 on 2024-01-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0015_remove_question_question_countdown_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-updated_at',)},
        ),
    ]
