# Generated by Django 5.0 on 2024-01-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0017_alter_answer_question_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='number_of_questions',
        ),
    ]
