# Generated by Django 5.0 on 2024-01-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0006_alter_otp_created_at_alter_otp_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile1-blue.svg', upload_to='profile_images'),
        ),
    ]
