# Generated by Django 5.0 on 2023-12-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnmathapp', '0002_alter_userverification_userverification_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
