# Generated by Django 5.0 on 2024-01-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnmathapp', '0005_rename_answers_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
