# Generated by Django 5.0 on 2024-01-02 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 2, 10, 53, 43, 641354)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 2, 10, 53, 43, 641354)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 2, 10, 53, 43, 641354)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 2, 10, 53, 43, 641354)),
        ),
    ]
