# Generated by Django 5.0 on 2024-01-02 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0002_alter_otp_created_at_alter_otp_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 2, 10, 54, 28, 76510)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 2, 10, 54, 28, 76510)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 2, 10, 54, 28, 76510)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 2, 10, 54, 28, 76510)),
        ),
    ]
