# Generated by Django 5.0 on 2023-12-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0002_alter_users_is_active_alter_users_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=50)),
                ('verification_token', models.CharField(max_length=100)),
                ('timeout', models.DateTimeField()),
                ('type', models.CharField(max_length=25)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
