# Generated by Django 5.0 on 2023-12-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0004_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
